# Site settings
title: GitHub Page Test
email: shiu.patricia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yeap this is a GitHub Page Test
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: patpot
github_username:  patshiu

# Build settings
markdown: kramdown
